/*****************************************************************************
 * Joseph Zambreno
 * Department of Electrical and Computer Engineering
 * Iowa State University
 *****************************************************************************/


/*****************************************************************************
 * resources.hpp - audio and texture enumerated types for the FloraVsUndead
 * application.
 *
 *
 * NOTES:
 * 2/18/13 by JAZ::Design created.
 *****************************************************************************/

#pragma once


/* Texture file enum */
typedef enum {TEX_BACKGROUND=0, TEX_COURT, TEX_SCOREBOARD_BOTTOM, TEX_SCOREBOARD_TOP,
              GREEN_FONT, RED_FONT, WHITE_FONT, NUM_TEXTURES, ZOMBIES} TEXTURE_ENUM;
extern std::string texFiles[NUM_TEXTURES];


/* Depth enum */
typedef enum {FRONT_DEPTH=0, FONT_DEPTH, OBJECT_DEPTH, SCOREBOARD_DEPTH, BACKGROUND_DEPTH, COURT_DEPTH, BACK_DEPTH, ZOMBIES_DEPTH} DEPTH_ENUM;


/* Sound effect file enum */
typedef enum {SFX_GROAN, SFX_GROAN2, SFX_GROAN3, SFX_GROAN4, SFX_GROAN5, SFX_GROAN6, NUM_SFX} SFX_ENUM;
extern std::string sfxFiles[NUM_SFX];


/* Music  file enum */
typedef enum {MUSIC_INTRO1, MUSIC_MAIN1, MUSIC_MAIN2, MUSIC_MAIN3, MUSIC_MAIN4, MUSIC_MAIN5,
                NUM_MUSIC} MUSIC_ENUM;
extern std::string musicFiles[NUM_MUSIC];


/* Sprite enums for the various font maps. We do this so that the resource arrays can be
 * accessed simply from getTexCoords() */
/* Sprite enum for TEX_BACKGROUND */
typedef enum {BACKGROUND_ALL=0, NUM_TEX_BACKGROUND} TEX_BACKGROUND_ENUM;
extern uint16_t tex_background_spriteMap[][4];

/* Sprite enum for TEX_COURT */
typedef enum {COURT_ALL=0, NUM_TEX_COURT} TEX_COURT_ENUM;
extern uint16_t tex_court_spriteMap[][4];

/* Sprite enum for TEX_SCOREBOARD_BOTTOM */
typedef enum {SCOREBOARD_BOTTOM_ALL=0, NUM_TEX_SCOREBOARD_BOTTOM} TEX_SCOREBOARD_BOTTOM_ENUM;
extern uint16_t tex_scoreboard_bottom_spriteMap[][4];

/* Sprite enum for TEX_SCOREBOARD_TOP */
typedef enum {SCOREBOARD_TOP_ALL=0, NUM_TEX_SCOREBOARD_TOP} TEX_SCOREBOARD_TOP_ENUM;
extern uint16_t tex_scoreboard_top_spriteMap[][4];


/* Sprite enum for GREEN_FONT */
typedef enum {GREEN_ZERO=0, GREEN_1, GREEN_2, GREEN_3, GREEN_4, GREEN_5, GREEN_6, GREEN_7, GREEN_8, GREEN_9, GREEN_NEG, NUM_GREEN_FONT} GREEN_FONT_ENUM;
extern uint16_t green_font_spriteMap[][4];


/* Sprite enum for RED_FONT */
typedef enum {RED_ZERO=0, RED_1, RED_2, RED_3, RED_4, RED_5, RED_6, RED_7, RED_8, RED_9, RED_COLON, RED_DOT, NUM_RED_FONT} RED_FONT_ENUM;
extern uint16_t red_font_spriteMap[][4];

/* Sprite enum for WHITE_FONT */
typedef enum {WHITE_A=0, WHITE_B, WHITE_C, WHITE_D, WHITE_E, WHITE_F, WHITE_G, WHITE_H, WHITE_I, WHITE_J, WHITE_K, WHITE_L, WHITE_M, WHITE_N, WHITE_O, WHITE_P, WHITE_Q, WHITE_R,
              WHITE_S, WHITE_T, WHITE_U, WHITE_V, WHITE_W, WHITE_X, WHITE_Y, WHITE_Z, WHITE_a, WHITE_b, WHITE_c, WHITE_d, WHITE_e, WHITE_f, WHITE_g, WHITE_h, WHITE_i, WHITE_j,
              WHITE_k, WHITE_l, WHITE_m, WHITE_n, WHITE_o, WHITE_p, WHITE_q, WHITE_r, WHITE_s, WHITE_t, WHITE_u, WHITE_v, WHITE_w, WHITE_x, WHITE_y, WHITE_z, WHITE_0, WHITE_1,
              WHITE_2, WHITE_3, WHITE_4, WHITE_5, WHITE_6, WHITE_7, WHITE_8, WHITE_9, NUM_WHITE_FONT} WHITE_FONT_ENUM;
extern uint16_t white_font_spriteMap[][4];

/*Sprite enum for ZOMBIES */
typedef enum {ZOMBIE_BUCKET_1 = 0, ZOMBIE_BUCKET_2, ZOMBIE_BUCKET_3, ZOMBIE_CONE_1, ZOMBIE_CONE_2, ZOMBIE_CONE_3, ZOMBIE_DANCER_HEAD, ZOMBIE_DANCER_BELT, ZOMBIE_DANCER_BODY_1,
ZOMBIE_DANCER_BODY_2, ZOMBIE_DANCER_COLAR, ZOMBIE_DANCER_EARING, ZOMBIE_DANCER_HAIR, ZOMBIE_DANCER_INNERARM_HAND, ZOMBIE_DANCER_INNERARM_LOWER, ZOMBIE_DANCER_INNERARM_UPPER,
ZOMBIE_DANCER_INNERLEG_FOOT, ZOMBIE_DANCER_INNERLEG_LOWER, ZOMBIE_DANCER_INNERLEG_UPPER, ZOMBIE_DANCER_OUTERARM_HAND, ZOMBIE_DANCER_OUTERARM_LoWER, ZOMBIE_DANCER_OUTERARM_UPPER,
ZOMBIE_DANCER_OUTERLEG_FOOT, ZOMBIE_DANCER_OUTERLEG_LOWER, ZOMBIE_DNCER_OUTERLEG_TOE, ZOMBIE_DANCE_OUTERLEG_UPPER, ZOMBIE_DIGGER_BODY, ZOMBIE_DIGGER_DIG_0, ZOMBIE_DIGGER_DIG_1,
ZOMBIE_DIGGER_DIG_2, ZOMBIE_DIGGER_DIG_3, ZOMBIE_DIGGER_DIG_4, ZOMBIE_DIGGER_DIG_5, ZOMBIE_DIGGER_DIRT, ZOMBIE_DIGGER_HARDHAT, ZOMBIE_DIGGER_HARDHAT_2, ZOMBIE_DIGGER_HARDHAT_3,
ZOMBIE_DIGGER_HEAD, ZOMBIE_DIGGER_INNERARM_HAND, ZOMBIE_DIGGER_INNERARM_LOWER, ZOMBIE_DIGGER_INNERARM_UPPER, ZOMBIE_DIGGER_INNERLEG_FOOT, ZOMBIE_DIGGER_INNGERLEG_LOWER, ZOMBIE_DIGGER_INNERLEG_UPPER,
ZOMBIE_DIGGER_JAW, ZOMBIE_DIGGER_OUTERARM_HAND, ZOMBIE_DIGGER_OUTERARM_LOWER, ZOMBIE_DIGGER_OUTERARM_UPPER, ZOMBIE_DIGGER_OUTERARM_UPPER_2, ZOMBIE_DIGGER_OUTERLEG_FOOT, ZOMBIE_DIGGER_OUTERLEG_LOWER,
ZOMBIE_DIGGER_OUTERLEG_UPPER, ZOMBIE_DIGGER_PICKAXE, ZOMBIE_DIGGER_RISE_GROUND, ZOMBIE_DIGGER_RISE_2, ZOMBIE_DIGGER_RISE_3, ZOMBIE_DIGGER_RISE_4, ZOMBIE_DIGGER_RISE_5, ZOMBIE_DIGGER_RISE_6,
ZOMBIE_EYE, ZOMBIE_FLAG_1, ZOMBIE_FLAG_3, ZOMBIE_FLAGHAND, ZOMBIE_FLAGPOLE, ZOMBIE_FOOBTBALL_HEAD, ZOMBIE_FOOBTBALL_HELMET, ZOMBIE_FOOBTBALL_HELMET_2, ZOMBIE_FOOBTBALL_HELMET_3,
ZOMBIE_FOOBTBALL_LEFTARM_EATINGHAND, ZOMBIE_FOOBTBALL_LEFTARM_EATINGLOWER, ZOMBIE_FOOBTBALL_LEFTARM_HAND, ZOMBIE_FOOBTBALL_LEFTARM_LOWER, ZOMBIE_FOOBTBALL_LEFTARM_UPPER,
ZOMBIE_FOOBTBALL_LEFTARM_UPPER_2, ZOMBIE_FOOBTBALL_LEFTLEG_FOOT, ZOMBIE_FOOBTBALL_LEFTLEG_LOWER, ZOMBIE_FOOBTBALL_LEFTLEG_UPPER, ZOMBIE_FOOBTBALL_LOWERBODY, ZOMBIE_FOOBTBALL_OUTERARM_EATING_HAND,
ZOMBIE_FOOBTBALL_RIGHTARM_HAND, ZOMBIE_FOOBTBALL_RIGHTARM_LOWER, ZOMBIE_FOOTBALL_RIGHTARM_UPPER, ZOMBIE_FOOBTBALL_RIGHTLEG_FOOT, ZOMBIE_FOOBTBALL_RIGHTLEG_LOWER, ZOMBIE_FOOBTBALL_RIGHTLEG_UPPER,
ZOMBIE_FOOTBALL_UPPERBODY, ZOMBIE_FOOBTBALL_UPPERBODY_2, ZOMBIE_FOOBTBALL_UPPERBODY_3, ZOMBIE_GLASSES, ZOMBIE_HAIR, ZOMBIE_HAND_ARM, ZOMBIE_HAND_FINGER1_1, ZOMBIE_HAND_FINGER1_2, ZOMBIE_HAND_FINGER2_1,
ZOMBIE_HAND_FINGER2_2, ZOMBIE_HAND_FINGER3_1, ZOMBIE_HAND_FINGER3_2, ZOMBIE_HAND_FINGER4_1, ZOMBIE_HAND_HAND, ZOMBIE_HAND_OVERLAY, ZOMBIE_HAND_ROCK_7, ZOMBIE_HAND_ROCK_1, ZOMBIE_HAND_ROCK_2, ZOMBIE_HAND_ROCK_3,
ZOMBIE_HAND_ROCK_4, ZOMBIE_HAND_ROCK_5, ZOMBIE_HAND_ROCK_6, ZOMBIE_HEAD, ZOMBIE_HEAD_GROSSOUT, ZOMBIE_HEAD_SUNGLASSES_1, ZOMBIE_HEAD_SUNGLASSES_2, ZOMBIE_HEAD_SUNGLASSES_3, ZOMBIE_HEAD_SUNGLASSES_4,
ZOMBIE_HEAD_2, ZOMBIE_INNERARM_HAND, ZOMBIE_INNERARM_LOWER, ZOMBIE_INNERARM_SCREENDOOR, ZOMBIE_INNERARM_SCREENDOOR_HAND, ZOMBIE_INNERARM_UPPER, ZOMBIE_INNERLEG_FOOT, ZOMBIE_INNERLEG_LOWER, ZOMBIE_INNERLEG_UPPER,
ZOMBIE_JAW, ZOMBIE_MUSTACHE_1, ZOMBIE_MUSTACHE_2, ZOMBIE_MUSTACHE_3, ZOMBIE_NECK, ZOMBIE_OUTERARM_HAND, ZOMBIE_OUTERARM_HAND_2, ZOMBIE_OUTERARM_LOWER, ZOMBIE_OUTERARM_SCREENDOOR, ZOMBIE_OUTERARM_UPPER,
ZOMBIE_OUTERARM_UPPER_2, ZOMBIE_OUTERLEG_FOOT, ZOMBIE_OUTERLEG_LOWER, ZOMBIE_OUTERLEG_UPPER, ZOMBIE_YETI_BODY, ZOMBIE_YETI_HEAD, ZOMBIE_YETI_INNERARM_HAND, ZOMBIE_YETI_INNERARM_LOWER, ZOMBIE_YETI_INNERARM_UPPER,
ZOMBIE_YETI_INNERLEG_FOOT, ZOMBIE_YETI_INNERLEG_LOWER, ZOMBIE_YETI_INNERLEG_UPPER, ZOMBIE_YETI_JAW, ZOMBIE_YETI_OUTERARM_HAND, ZOMBIE_YETI_OUTERARM_LOWER, ZOMBIE_YETI_OUTERARM_UPPER, ZOMBIE_YETI_OUTERARM_UPPER_2,
ZOMBIE_YETI_OUTERLEG_FOOT, ZOMBIEARM, ZOMBIEBODY, NUM_ZOMBIES} NUM_ZOMBIES_ENUM;
extern uint16_t zombie_object_spriteMap[][4];


/*NOTED OUT FOR NOW, UNNOTE LATER

typedef enum {ANIM_SPROUT, CABBAGEPULT_BASKET, CABBAGEPULT_BASKET_OVERLAY, CABBAGEPULT_BASKETVINE_1, CABBAGEPULT_BASKETVINE_2, CABBAGEPULT_BASKETVINE_3, CABBAGEPULT_BASKETVINE_4,
CABBAGEPULT_BLINK_1, CABBAGEPULT_BLINK_2, CABBAGEPULT_CABBAGE, CABBAGEPULT_EYEBROW, CABBAGEPULT_EYEBROW_1, CABBAGEPULT_EYEBROW_2, CABBAGEPULT_HEAD, CABBAGEPULT_LEAF, CABBAGEPULT_STALK_1,
CABBAGEPULT_STALK_2, CABBAGEPULT_STALK_3, CABBAGEPULT_STALK_4, CABBAGEPULT_STALK_5, CACTUS_ARM_1_1, CACTUS_ARM_1_2, CACTUS_ARM_2_1, CACTUS_ARM_2_2, CACTUS_BLINK_1, CACTUS_BLINK_2, CACTUS_BODY_OVERLAY,
CACTUS_BODY_OVERLAY_2, CACTUS_BODY_1, CACTUS_BODY_2, CACTUS_BODY_3, CACTUS_FLOWER, CACTUS_FLOWER_TOP, CACTUS_LIPS, CHERRYBOMB_LEAF_1, CHERRYBOMB_LEAF_1_TIP, CHERRYBOMB_LEAF_2, CHERRYBOMB_LEAF_2_TIP,
CHERRYBOMB_LEAF_3, CHERRYBOMB_LEFT_1, CHERRYBOMB_LEFT_3, CHERRYBOMB_LEFTEYE_1_1, CHERRYBOMB_LEFTEYE_1_2, CHERRYBOMB_LEFTEYE_1_3, CHERRYBOMB_LEFTEYE_1_4, CHERRYBOMB_LEFTEYE_1_5,
CHERRYBOMB_LEFTEYE_2_1, CHERRYBOMB_LEFTEYE_2_2, CHERRYBOMB_LEFTEYE_2_3, CHERRYBOMB_LEFTEYE_2_4, CHERRYBOMB_LEFTEYE_2_5, CHERRYBOMB_LEFTMOUTH_1, CHERRYBOMB_LEFTMOUTH_2, CHERRYBOMB_LEFTMOUTH_3,
CHERRYBOMB_LEFTMOUTH_4, CHERRYBOMB_LEFTMOUTH_5, CHERRYBOMB_LEFTSTEM, CHERRYBOMB_RIGHT_1, CHERRYBOMB_RIGHT_3, CHERRYBOMB_RIGHTEYE_1_1, CHERRYBOMB_RIGHTEYE_1_2, CHERRYBOMB_RIGHTEYE_1_3, CHERRYBOMB_RIGHTEYE_1_4,
CHERRYBOMB_RIGHTEYE_1_5, CHERRYBOMB_RIGHTEYE_2_1, CHERRYBOMB_RIGHTEYE_2_2, CHERRYBOMB_RIGHTEYE_2_3, CHERRYBOMB_RIGHTEYE_2_4, CHERRYBOMB_RIGHTEYE_2_5, CHERRYBOMB_RIGHTMOUTH_1, CHERRYBOMB_RIGHTMOUTH_2,
CHERRYBOMB_RIGHTMOUTH_3, CHERRYBOMB_RIGHTMOUTH_4, CHERRYBOMB_RIGHTMOUTH5, CHERRYBOMB_RIGHTSTEM, CHOMPER_BOTTOMLIP, CHOMPER_GROUNDLEAF_1, CHOMPER_GROUNDLEAF_1_TIP, CHOMPER_GROUNDLEAF_2, CHOMPER_GROUNDLEAF_2_TIP,
CHOMPER_GROUNDLEAF_3, CHOMPER_GROUNDLEAF_4, CHOMPER_HEADLEAF_1, CHOMPER_HEADLEAF_2, CHOMPER_HEADLEAF_3, CHOMPER_HEADLEAF_4, CHOMPER_INSIDEMOUTH, CHOMPER_SPIKE, CHOMPER_STEM_1, CHOMPER_STEM_2, CHOMPER_STEM_3,
CHOMPER_STOMACH, CHOMPER_TONGUE, CHOMPER_TOPJAW, CHOMPER_UNDERJAW, DOOMSHROOM_EXPLOSION_TOP, FUMESHROOM_BLINK_1, FUMESHROOM_BLINK_2, FUMESHROOM_BODY, FUMESHROOM_HEAD, FUMESHROOM_SPOUT, FUMESHROOM_TIP,
GATLINGPEA_BARREL, GATLINGPEA_BLINK_1, GATLINGPEA_BLINK_2, GATLINGPEA_HEAD, GATLINGPEA_HELMET, GATLINGPEA_MOUTH, GATLINGPEA_MOUTH_OVERLAY, JALAPENO_BODY, JALAPENO_BODY_2, JALAPENO_CHEEK, JALAPENO_EYE_1,
JALAPENO_EYE_2, JALAPENO_EYEBROW_1, JALAPENO_EYEBROW_2, JALAPENO_MOUTH, JALAPENO_STEM, LILYPAD_BODY, MELONPULT_BLINK_1, MELONPULT_BLINK_2, MELONPULT_BODY, MELONPULT_EYEBROW, MELONPULT_MELON, MELONPULT_STALK,
MONEYBAG, MONEYBAG_HI_RES, PEA_PARTICLES, PEA_SPLATS, PEASHOOTER_BACKLEAF, PEASHOOTER_BACKLEAF_LEFTTIP, PEASHOOTER_BACKLEAF_RIGHTTIP, PEASHOOTER_BLINK_1, PEASHOOTER_BLINK_2, PEASHOOTER_EYEBROW,
PEASHOOTER_FRONTLEAF, PEASHOOTER_FRONTLEAF_LEFTTIP, PEASHOOTER_FRONTLEAF_RIGHTTIP, PEASHOOTER_HEAD, PEASHOOTER_HEADLEAF_2RDFARTHEST, PEASHOOTER_HEADLEAF_3RDFARTHEST, PEASHOOTER_HEADLEAF_FARTHEST,
PEASHOOTER_HEADLEAF_NEAREST, PEASHOOTER_HEADLEAF_TIP_BOTTOM, PEASHOOTER_HEADLEAF_TIP_TOP, PEASHOOTER_LIPS, PEASHOOTER_MOUTH, PEASHOOTER_SPROUT, PEASHOOTER_STALK_BOTTOM, PEASHOOTER_STALK_TOP, PORTAL_CIRCLE_CENTER,
PORTAL_CIRCLE_GLOW, PORTAL_CIRCLE_OUTER, POT_BOTTOM, POT_BOTTOM_2, POT_GLOW, POT_LEAF1, POT_LEAF2, POT_SHADOW, POT_STEM, POT_TOP, POT_TOP_DARK, POT_WATER_BASE, POT_WATER_TOP, POT_WATER_TOP_GLOW, POTATOMINE_BLINK_1,
POTATOMINE_BLINK_2, POTATOMINE_BODY, POTATOMINE_EYES, POTATOMINE_LIGHT_1, POTATOMINE_LIGHT_2, POTATOMINE_MASHED, POTATOMINE_PARTICLES, POTATOMINE_ROCK_1, POTATOMINE_ROCK_2, POTATOMINE_ROCK_3, POTATOMINE_ROCK_4,
POTATOMINE_ROCK_5, POTATOMINE_ROCK_6, POTATOMINE_STEM, POTATOMINEFLASH, PROJECTILE_STAR, PROJECTILECACTUS, PROJECTILEPEA, PUFF_1, PUFF_2, PUFF_3, PUFF_4, PUFF_5, PUFF_6, PUFF_7, PUFFSHROOM_BLINK_1, PUFFSHROOM_BLINK_2,
PUFFSHROOM_BODY, PUFFSHROOM_HEAD, PUFFSHROOM_PUFF_1, PUFFSHROOM_PUFF_2, PUFFSHROOM_STEM, PUFFSHROOM_TIP, SHOVEL_HI_RES, TALLNUT_BLINK_1, TALLNUT_BLINK_2, TALLNUT_BODY, TALLNUT_CRACKED_1, TALLNUT_CRACKED_2,
WALLNUT_BLINK1, WALLNUT_BLINK2, WALLNUT_BODY, WALLNUT_CRACKED_1, WALLNUT_CRACKED_2, WALLNUT_TWITCH} NUM_OBJECTS_ENUM;
extern uint16_t objects_spritemap[][4];

*/

